
// initialize Event class only once
if (typeof initEvent == "undefined") {

    initEvent = new Event();

}

// get and render all events from server
initEvent.getEvents();

/* A callback for click book button listener 
* params: event Id:string
*/
bookEventHandler = async (eventId) => {


    console.log(eventId);

    // call beställ biljett method 
    const result = await initEvent.bestallBiljett(eventId);

    // log response   result
    console.log(result);

    // check if we a new biljett is generated by backend
    if (result.id) {
        alert("Din Biljett är: " + result.id);
        // update the page to reflect biljetter kvar data on trhe events list
        location.reload();
    } else {
        // alert the user with any error occurs
        alert(result.message);
    }


}

