// initialize Event class only once
if (typeof initEvent == "undefined") {

    initEvent = new Event();

}
bestall = async ()=> { 

 var eventId = location.search.split('eventId=')[1];



    console.log(eventId);

    // call beställ biljett method 
    const result = await initEvent.bestallBiljett(eventId);

    // log response   result
    console.log(result);

    // check if we a new biljett is generated by backend
    if (result.id) {

        const eventObj = await initEvent.getSingleEvent(eventId);

       // alert("Din Biljett är: " + result.id);

        initEvent.renderTicket(eventObj,  result.id);

        // update the page to reflect biljetter kvar data on trhe events list
     //   location.reload();
    } else {
        // notify the user with any error occurs
        //alert(result.message);
        document.querySelector("#result").innerHTML = `${result.message}`;
    }

};
bestall();


//}
