// initialize Event class only once
if (typeof initEvent == "undefined") {

    initEvent = new Event();

}
bestall = async ()=> { 

 var eventId = location.search.split('eventId=')[1];


    // call beställ biljett method 
    const result = await initEvent.bestallBiljett(eventId);

    // log response   result
    console.log(result);

    // check if we a new biljett is generated by backend
    if (result.id) {
        
        // get event details from server
        const eventObj = await initEvent.getSingleEvent(eventId);

        // render the ticket
        initEvent.renderTicket(eventObj,  result.id);

    } else {

        // notify the user with any error occurs
        document.querySelector("#result").innerHTML = `${result.message}`;
    }

};

bestall();
